### PR TITLE
lazy fix by omitting error if you try to buy your own product.

### LINKED ISSUE #92: disable buying of own product
disable button
error handling nicer

### PR DESCRIPTION
**Pull request by Dnupselina**
Closes #92

### CODE REVIEW

File: backend/src/controllers/products.controller.ts [hunk 1]
```diff
@@ -127,6 +128,7 @@ productController.put(
 productController.use(
   '/:productId/transactions',
   verifyToken,
+  checkProductAuthorizationInverted,
```
Comment (CodeOneTwo) [inline backend/src/controllers/products.controller.ts:131]: nice.... looks like you understand the concept of middlewares. :wink: 


We have to be careful, that we're not overusing middlewares for database relevant checks. Otherwise we end up getting the product from database multiple times (high cost?) for quick checks that could be done in the end when we need to product anyway (another db query)

This is just an FYI and no changes are necessary
